# classic
alias cp="cp -i"                          # confirm before overwriting something
alias cp="mv -i"                          # confirm before overwriting something
alias cp="ln -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias more=less														# less is more
alias mkdir='mkdir -pv'

# ls
alias ls='ls -CF --color=auto'
alias la='ls -A'
alias ll='ls -alF'
alias lt='ls --human-readable --size -1 -S --classify'

# grep history
alias gh='history | grep'

# ssh-agent
alias evalssh='eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa'

# flameshot
alias flameshot='flameshot gui'

# git
alias gs='git status'
alias gc='git commit'
alias gb='git checkout'
alias gtl='cd $(git rev-parse --show-toplevel)'

# web server
alias ws='(firefox http://localhost:8000 &) && (python -m http.server 8000)'

# todo list
alias td='vi ~/Documents/todo.md'

# when firefox is buggy
alias killfirefox="kill $(ps aux | grep firefox$ | awk '{print $2}')"

# pacman
alias pacmanautoremove='pacman -Qtdq | sudo pacman -Rns -'
alias pacmanexplicitinstalled='pacman -Qqem'

# mount (replace with fstab entry)
alias mountnas='sudo mount -t cifs -o vers=2.0,username=rdiep,domain=osmozis //nas.osmoziswifi.com/osmozis /mnt/nas/'
alias mounthome='sudo mount -t cifs -o vers=2.0,username=rdiep,domain=osmozis //nas.osmoziswifi.com/home /mnt/home/'

# vim bindings in info command
alias info='info --vi-keys'


# editor
vit()
{
	if [[ ! -z "$VIM_TERMINAL" ]]; then
		if [ $# -eq 0 ]; then
			echo "You are already inside Vim. Provide filenames as arguments"
		else
			readlink -f $@ | xargs printf '\033]51;["call", "Tapi_vit", ["%s"]]\007'
		fi
	else
		vim $@
	fi
}
alias vi='vim'
alias vim='vit'
