alias evalssh='eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa'
alias ll='ls -l'
alias vi='vim'
alias killfirefox="kill $(ps aux | grep firefox$ | awk '{print $2}')"
alias pacmanautoremove='pacman -Qtdq | sudo pacman -Rns -'
